use master;
go;

create database pioopublicidade;
go;

use pioopublicidade;

GO;

CREATE TABLE CATEGORIA(
[GUID] VARCHAR(40) NOT NULL PRIMARY KEY,
[NOME] VARCHAR(50) NOT NULL
);
GO;
CREATE TABLE ANUNCIANTE (
[GUID] VARCHAR(40) NOT NULL PRIMARY KEY,
[NOME] VARCHAR(100),
[DOCUMENTO] VARCHAR(30),
[ENDERECO] VARCHAR(150),
[TELEFONE] VARCHAR(20),
[DATACRIACAO] DATETIME DEFAULT GETDATE()
);
GO;
CREATE TABLE ANUNCIO (
[GUID] VARCHAR(40) NOT NULL PRIMARY KEY,
[GUIDANUNCIANTE] VARCHAR(40) NOT NULL,
[GUIDCATEGORIA] VARCHAR(40) NOT NULL,
[DATAVALIDADE] DATETIME NOT NULL,
[DATACRIACAO] DATETIME DEFAULT GETDATE()
)

ALTER TABLE ANUNCIO ADD CONSTRAINT ANUNCIO_GUIDANUNCIANTE FOREIGN KEY (GUIDANUNCIANTE) REFERENCES ANUNCIANTE([GUID])
ALTER TABLE ANUNCIO ADD CONSTRAINT ANUNCIO_GUIDCATEGORIA FOREIGN KEY (GUIDCATEGORIA) REFERENCES CATEGORIA([GUID])

