
CREATE TABLE `pioopublicidade`.`categoria` (
  `GUID` VARCHAR(40) NOT NULL,
  `NOME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`GUID`));


CREATE TABLE `pioopublicidade`.`anunciante` (
`GUID` VARCHAR(40) NOT NULL,
`NOME` VARCHAR(100),
`DOCUMENTO` VARCHAR(30),
`ENDERECO` VARCHAR(150),
`TELEFONE` VARCHAR(20),
`DATACRIACAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`GUID`))

CREATE TABLE `pioopublicidade`.`anuncio` (
`GUID` VARCHAR(40) NOT NULL,
`GUIDANUNCIANTE` VARCHAR(40) NOT NULL,
`GUIDCATEGORIA` VARCHAR(40) NOT NULL,
`DATAVALIDADE` DATETIME NOT NULL,
`DATACRIACAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(`GUID`)
)

CREATE TABLE `pioopublicidade`.`usuario` (
  `GUID` VARCHAR(40) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`GUID`));


ALTER TABLE anuncio 
ADD FOREIGN KEY (`GUIDANUNCIANTE`) REFERENCES ANUNCIANTE(`GUID`)

ALTER TABLE anuncio 
ADD FOREIGN KEY (`GUIDCATEGORIA`) REFERENCES CATEGORIA(`GUID`)

ALTER TABLE `pioopublicidade`.`anunciante` 
ADD COLUMN `CIDADE` VARCHAR(45) NULL AFTER `DATACRIACAO`;

SELECT ANUNCIO.GUID, ANUNCIO.GUIDANUNCIANTE, ANUNCIO.GUIDCATEGORIA, ANUNCIO.DATAVALIDADE, ANUNCIO.DATACRIACAO, ANUNCIANTE.NOME, ANUNCIANTE.DOCUMENTO, ANUNCIANTE.ENDERECO, ANUNCIANTE.TELEFONE, 
                  CATEGORIA.NOME AS CATEGORIANOME
FROM     ANUNCIO INNER JOIN
                  ANUNCIANTE ON ANUNCIANTE.GUID = ANUNCIO.GUIDANUNCIANTE INNER JOIN
                  CATEGORIA ON CATEGORIA.GUID = ANUNCIO.GUIDCATEGORIA